version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=your_secret_key_here
      - DJANGO_DEBUG=TRUE
      - DATABASE=POSTGRESQL
      - NAME=mydatabase
      - USER=mydatabaseuser
      - PASSWORD=mypassword
      - HOST=db
      - PORT=5432
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=mydatabaseuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"

volumes:
  postgres_data: